apiVersion: v1
kind: Pod
metadata:
  name: http-server-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "echo 'HTTP/1.1 200 OK\n\nhello\n' | nc -l -p 8080"]
    ports:
    - containerPort: 8080

